### ISSUE TITLE
Extra's not being correctly set

### ISSUE THREAD

**Issue by blxrr** [alberttheprince/popcornrp-customs#1]
Hello,

So, the extras will say "Disabled" even if they're enabled and sometimes "Enabled" is disabled instead so it's not correctly gathering the extras and whether they're disabled/enabled before going into the customs.

**Comment by Jorn08** [comment]
From the testing I did it does seem like it makes more sense to switch enabled and disabled around. The issue where sometimes enabled is disabled only seems to occur with add-on vehicles, don't think this can be 'fixed'.

**Comment by blxrr** [comment]
> From the testing I did it does seem like it makes more sense to switch enabled and disabled around. The issue where sometimes enabled is disabled only seems to occur with add-on vehicles, don't think this can be 'fixed'.

I didn't get to test stock GTA vehicles now that you mention it, but that makes sense.

**Comment by Jorn08** [comment]
#2 has been merged
