### ISSUE TITLE
Some things don't disable even after commenting them out

### ISSUE THREAD

**Issue by ThisIsRigged** [alberttheprince/popcornrp-customs#11]
I'm trying to set this up only for my mrpd mechanic so they can repair and change liveries
But even after commenting them out in the config wheels and installing a turbo is still on

**Comment by Jorn08** [comment]
If you want to disable turbo, comment out these lines.
https://github.com/alberttheprince/popcornrp-customs/blob/main/client/menus/performance.lua#L63-L77
