### ISSUE TITLE
Once applying a livery, it doesn't allow you to change to another.

### ISSUE THREAD

**Issue by LukeeeChan** [alberttheprince/popcornrp-customs#12]
Self-explanatory.

**Comment by Jorn08** [comment]
Could you elaborate, I am not able to reproduce this issue. What vehicle are you testing this with?

**Comment by lush0n3** [comment]
Hi @Jorn08  I have the same problem and I have a few things that might help

Video: https://streamable.com/7dr27c

Passes only with native GTA V vehicles

When you apply a decoration and save the vehicle, the decoration options do not appear again and the return value of the function is 0.

This only happens with vehicles that come with covers outside of the vehicle's YTD file.

I am using es_extended and loaf_garage.

I will be reviewing any comments to continue helping.

**Comment by LukeeeChan** [comment]
Any update on this @lush0n3 ??

**Comment by alberttheprince** [comment]
Can you tell me if this still an issue? We recently did a fix related to props.

**Comment by LukeeeChan** [comment]
Still the same for me. @alberttheprince

**Comment by Jorn08** [comment]
Can you repro this with a vehicle from the base game?

**Comment by LukeeeChan** [comment]
> Can you repro this with a vehicle from the base game?

It works fine with a base game vehicle; add-on vehicles don't work.

**Comment by alberttheprince** [comment]
> Can you repro this with a vehicle from the base game?

Trying this on our server also has the same issue, we only use base/vanilla.

**Comment by LukeeeChan** [comment]
> > Can you repro this with a vehicle from the base game?
> 
> Trying this on our server also has the same issue, we only use base/vanilla.

I haven't found a fix yet unfortunately.

**Comment by alberttheprince** [comment]
@LukeeeChan @lush0n3 fix is now added, please replace livery.lua.
