### ISSUE TITLE
Need some management system

### ISSUE THREAD

**Issue by AntonMars** [alberttheprince/popcornrp-customs#13]
Hi, awesome script!

As I see it, the mech can do the upgrades for free and then we can use a billing script to charge the customer. But how can I as the shop owner get my cut from the upgrade? i.e. the mech should get like 30% and the shop should get the 70%. Now the mech can just charge anything and basically 'steals' from the shop. Is there a way to add some function to see how much the mech has made or a way to transfer the 70% to a society account? Also thinking the mech can just do a free upgrade and then collect a % from his 'friends' later when he's off duty. Need to be able to see how much 'stock' was used by each mech.

**Comment by Jorn08** [comment]
This resource is not meant to be used as a management system for mechanics, just to simply modify your vehicle.
