### ISSUE TITLE
Suggestion

### ISSUE THREAD

**Issue by d3adshot-4** [alberttheprince/popcornrp-customs#18]
Can u plz add upgrade receipt feature so the mechanic has to do the upgrades

**Comment by alberttheprince** [comment]
if you add   job = { 'mechanic'}, it will only allow mechanics to do upgrades at those spots.

**Comment by DJJackal** [comment]
> if you add job = { 'mechanic'}, it will only allow mechanics to do upgrades at those spots.

Where do we input this code and in what file? I've been checking but cant seem to find where it would go ...
