### ISSUE TITLE
Console Error

### ISSUE THREAD

**Issue by ziokoko** [alberttheprince/popcornrp-customs#21]
I keep getting this error in the console. Is this because the person doesn't own the car? I do the own the car.
![image](https://github.com/alberttheprince/popcornrp-customs/assets/134436521/3a0ebf1d-1fec-4c7f-9278-d5584d71463d)

**Comment by alberttheprince** [comment]
Please use this updated fxmanifest, it should fix the issue.

https://github.com/alberttheprince/popcornrp-customs/blob/main/fxmanifest.lua
