### ISSUE TITLE
MySQL Global Error in Console

### ISSUE THREAD

**Issue by OnyxEye-RCG** [alberttheprince/popcornrp-customs#29]
We're getting this error in console when people edit their vehicles. Everything still seems to save ok, though. It's just having problems checking ownership. We're using oxmysql, but it's supposed to be backwards compatible with MySQL, I thought.
`[script:popcornrp-cus] SCRIPT ERROR: @popcornrp-customs/server.lua:80: attempt to index a nil value (global 'MySQL')
[script:popcornrp-cus] > IsVehicleOwned (@popcornrp-customs/server.lua:80)
[script:popcornrp-cus] > handler (@popcornrp-customs/server.lua:93)`

**Comment by Jorn08** [comment]
Did you change something in the manifest? There should be an `'@oxmysql/lib/MySQL.lua'` dependency in `server_scripts`

**Comment by OnyxEye-RCG** [comment]
My apologies. I was using an older version that did not have that in the fxmanifest and didn't realize it. I updated today and that error no longer exists.
