### ISSUE TITLE
Can't set Mechanic Tow Vehicle

### ISSUE THREAD

**Issue by DJJackal** [alberttheprince/popcornrp-customs#31]
Might be a stupid question. But I can't seem to find where you can set what vehicles a Mechanic can use to Tow with, ie flatbed truck.

Anyone can help would be greatly appreciated.

**Comment by alberttheprince** [comment]
This is not part of popcornrp-customs, this is only the menu/abilities related to the menu. If you'd like to make a feature like this, I'd suggest adding it as a separate resource or using some kind of job garage system.
