### ISSUE TITLE
OXLib updated

### ISSUE THREAD

**Issue by Max-Ridderikhoff** [alberttheprince/popcornrp-customs#32]
Hi, OXLib updated and now there are errors in the console when trying to open the script;

SCRIPT ERROR: @ox_lib/imports/require/client.lua:82: @popcornrp-customs/client/menus/main.lua:156: <eof> expected near 'local'

Is there gonna be a fix for this?

Thanks in advance

**Comment by alberttheprince** [comment]
There is no line 156 in main.lua:

https://github.com/alberttheprince/popcornrp-customs/blob/7f22d9b76ba0dbbec7dbfdee3722ec6aaa6a3571/client/menus/main.lua#L153

It seems you edited this?

**Comment by Max-Ridderikhoff** [comment]
For some reason there was a local variable being declared, now it works thanks!
