### ISSUE TITLE
Could not make hard link

### ISSUE THREAD

**Issue by SpeedoCorleone** [alberttheprince/popcornrp-customs#33]
Getting error message

 `[ citizen-server-impl] Could not make hard link for /home/REDACTED/gta5-fivem-txadmin/QBCoreFramework_AEC3CA.base/resources//popcornrp-customs/stream//vehicle_paint_ramps.ytd <-> /home/REDACTED/g634720/gta5-fivem-txadmin/QBCoreFramework_AEC3CA.base/cache/files/popcornrp-customs/stream_cache/zcaf5c223728c8e43279122018afa05444166e118.`

Any ideas?

**Comment by alberttheprince** [comment]
Could you give more context or information? Can't tell you anything based on this error message alone.

**Comment by SpeedoCorleone** [comment]
Brand new server, first two scripts I tried to install were this and ox_lib. No errors anywhere except for this error, no options in any shops to modify/repair vehicles.

**Comment by alberttheprince** [comment]
Have you tried reinstalling? Possible the stream files were corrupted at some point? Never seen this error and not sure what would cause it.

**Comment by SpeedoCorleone** [comment]
To reinstall do I just delete the resources directory, comment out the ensure, reboot the server, add back in the ensure and resources directory, and reboot again?

**Comment by alberttheprince** [comment]
Just redownload it, delete the old old, and replace it with the new one.

**Comment by alberttheprince** [comment]
Anything new?

**Comment by alberttheprince** [comment]
Closed as no response given.
