### ISSUE TITLE
Dashboard / Interior Colour not showing in menu

### ISSUE THREAD

**Issue by zxG-J** [alberttheprince/popcornrp-customs#9]
Hey! 

With some vehicles it doesn't show the option to change interior/dashboard colour when they can be changed via vMenu etc

**Comment by alberttheprince** [comment]
@Jorn08 This seems to be an issue, there are some dashboard/interior options missing

**Comment by zxG-J** [comment]
Even if it just gets enabled for all cars, and will only paint if the car has it 😀

**Comment by zxG-J** [comment]
As in always shows in the menu
